"""Research agent package powered by pydantic-deepagents.

Research reports are generated by a ``create_deep_agent`` agent from the
`pydantic-deep` package (docs: https://vstorm-co.github.io/pydantic-deepagents/):

- The agent gets custom tools that query the private verity-rag document
  store (``rag_search``, ``list_collections``, ``get_report_image``) via
  ``ctx.deps``.
- Web search (https://pydantic.dev/docs/ai/capabilities/web-search/) and
  page fetch (https://pydantic.dev/docs/ai/capabilities/web-fetch/) are
  enabled by default so the agent can extend the internal findings with
  up-to-date public information. Page fetch runs through a **local**
  markdownify-based tool by default (``WebFetch(native=False, local=True)``)
  so it works with every Anthropic-compatible gateway — most gateways
  (e.g. DeepSeek) reject Anthropic's server-side ``web_fetch_20250910`` tool.
- Structured output is enforced with ``output_type=ResearchReport`` — the
  model must produce a validated report, so there is no manual JSON
  wrangling or tool-call fallback logic.

The package is split by responsibility:

- :mod:`~mysterium.agents.models` — the structured output schema
  (``ResearchReport`` and friends).
- :mod:`~mysterium.agents.deps` — agent dependencies (``ResearchDeps``).
- :mod:`~mysterium.agents.tools` — the private RAG tools.
- :mod:`~mysterium.agents.prompt` — the research system prompt.
- :mod:`~mysterium.agents.progress` — streamed progress-phase labels.
- :mod:`~mysterium.agents.research` — agent factory + report generation.
- :mod:`~mysterium.agents.chat` — the conversational Q&A agent (see that
  module).

Public API (re-exported here for backward compatibility):

- :func:`generate_research_report` / :func:`stream_research_report`
- :class:`ResearchReport` and the schema models
- :class:`ResearchDeps`
"""

from mysterium.agents.deps import ResearchDeps
from mysterium.agents.models import (
    ReportImage,
    ReportSection,
    ResearchReport,
    SourceCitation,
)
from mysterium.agents.research import (
    generate_research_report,
    stream_research_report,
)

__all__ = [
    "ResearchDeps",
    "ResearchReport",
    "SourceCitation",
    "ReportImage",
    "ReportSection",
    "generate_research_report",
    "stream_research_report",
]
