"""Research agent powered by pydantic-deepagents.

Research reports are generated by a ``create_deep_agent`` agent from the
`pydantic-deep` package (docs: https://vstorm-co.github.io/pydantic-deepagents/):

- The agent gets custom tools that query the private verity-rag document
  store (``rag_search``, ``list_collections``) via ``ctx.deps``.
- Web search (https://pydantic.dev/docs/ai/capabilities/web-search/) and
  page fetch (https://pydantic.dev/docs/ai/capabilities/web-fetch/) are
  enabled by default so the agent can extend the internal findings with
  up-to-date public information. The fetch tool is separately toggleable
  because most Anthropic-compatible gateways reject it.
- Structured output is enforced with ``output_type=ResearchReport`` — the
  model must produce a validated report, so there is no manual JSON
  wrangling or tool-call fallback logic.
"""

from __future__ import annotations

import datetime
import logging
from dataclasses import dataclass, field
from typing import Any

import httpx
from pydantic import BaseModel, Field
from pydantic_ai import RunContext
from pydantic_ai.agent import Agent
from pydantic_ai.models.anthropic import AnthropicModel
from pydantic_ai.providers.anthropic import AnthropicProvider
from pydantic_deep import DeepAgentDeps, StateBackend, create_deep_agent

from mysterium.clients.rag_client import RAGClient

logger = logging.getLogger(__name__)


# ── Structured Output Models ────────────────────────────────────────


class SourceCitation(BaseModel):
    """A single source used in the report."""

    title: str = Field(description="Title or filename of the source")
    relevance: str = Field(description="Why this source was relevant to the research")
    excerpt: str = Field(description="Key excerpt from the source", max_length=500)


class ReportSection(BaseModel):
    """A section of the research report."""

    heading: str = Field(description="Section heading")
    content: str = Field(description="Section body text")
    sources: list[str] = Field(
        description="Source identifiers referenced in this section"
    )


class ResearchReport(BaseModel):
    """A structured research report synthesised from RAG and web sources."""

    title: str = Field(description="Report title")
    summary: str = Field(description="Executive summary (2-3 paragraphs)")
    key_findings: list[str] = Field(description="Key findings extracted from the research")
    sections: list[ReportSection] = Field(description="Detailed report sections")
    sources: list[SourceCitation] = Field(description="All sources cited in the report")
    gaps: list[str] = Field(
        description="Knowledge gaps or areas needing further research"
    )
    generated_at: str = Field(
        default="", description="ISO-8601 timestamp of generation"
    )


# ── Agent Dependencies ──────────────────────────────────────────────


@dataclass
class ResearchDeps(DeepAgentDeps):
    """Deep-agent dependencies extended with RAG access.

    The custom tools below read the verity-rag client and query settings
    from ``ctx.deps``, which pydantic-ai injects at call time.

    ``rag_client`` has a default factory only so the dataclass ordering rules
    allow the extra fields after ``DeepAgentDeps``' defaulted ones — every run
    passes a real client built from the request settings.
    """

    rag_client: RAGClient = field(default_factory=RAGClient)
    collection_name: str = "documents"
    rag_limit: int = 10


# ── Custom Tools (private RAG) ──────────────────────────────────────


async def rag_search(ctx: RunContext[ResearchDeps], query: str, limit: int = 5) -> str:
    """Search the private RAG document store for relevant excerpts.

    Use this to find information in the user's uploaded documents — it is the
    primary source material for the report. Each excerpt is labelled
    ``[n] Source: <filename> (score: ...)`` so you can cite it.

    Args:
        query: The natural-language search query.
        limit: Maximum number of excerpts to return (1-50, default 5).
    """
    limit = max(1, min(int(limit), 50))
    try:
        results = await ctx.deps.rag_client.search(
            query=query,
            collection_name=ctx.deps.collection_name,
            limit=limit,
        )
    except httpx.HTTPError as e:  # Return errors as strings so the agent can recover.
        logger.warning("rag_search failed for %r: %s", query, e)
        return f"RAG search failed: {e}"

    if not results:
        return (
            f"No documents in collection {ctx.deps.collection_name!r} matched "
            f"{query!r}. Note this in the report's knowledge gaps."
        )

    blocks = []
    for i, r in enumerate(results, 1):
        source = r.metadata.get("filename") or r.parent_doc_id or f"result-{i}"
        blocks.append(f"[{i}] Source: {source} (score: {r.score:.3f})\n{r.content}")
    return "\n\n---\n\n".join(blocks)


async def list_collections(ctx: RunContext[ResearchDeps]) -> str:
    """List the names of the available RAG document collections.

    Returns one collection name per line, or a short message when there are
    none.
    """
    try:
        collections = await ctx.deps.rag_client.list_collections()
    except httpx.HTTPError as e:
        logger.warning("list_collections failed: %s", e)
        return f"Listing RAG collections failed: {e}"
    if not collections:
        return "No document collections are available."
    return "\n".join(c.name for c in collections)


# ── Agent Factory ───────────────────────────────────────────────────


def _build_system_prompt() -> str:
    """System prompt describing the research workflow."""
    return (
        "You are a research synthesis agent. Produce a thorough, well-structured "
        "research report on the user's topic.\n\n"
        "## Workflow\n"
        "1. Use the `rag_search` tool to find relevant excerpts in the private "
        "document store. Start there — the user's documents are the primary "
        "source material.\n"
        "2. When the documents are thin, outdated, or the topic needs current "
        "public context, use web search and page fetches to fill the gaps. "
        "Prefer authoritative sources and record their URLs.\n"
        "3. Synthesise across all sources — do not just summarise each document "
        "in turn. Flag contradictions between sources.\n"
        "4. Cite specific excerpts: reference the `[n] Source: ...` labels from "
        "`rag_search`, and give URLs for web sources.\n"
        "5. Note knowledge gaps — what is missing, uncertain, or contradicted.\n\n"
        "## Report structure\n"
        "- Executive summary (2-3 paragraphs).\n"
        "- Key findings as short, specific bullets.\n"
        "- Detailed sections with clear headings.\n"
        "- A sources list: title, why it was relevant, and a key excerpt.\n"
        "- Knowledge gaps.\n"
        "- Write in a neutral, academic tone.\n"
        "If the RAG store returns nothing, say so explicitly in the gaps and "
        "produce the best report you can from web sources and general knowledge."
    )


def _build_research_agent(
    *,
    model: str,
    api_key: str,
    base_url: str = "",
    max_tokens: int,
    use_web: bool,
    web_fetch: bool,
) -> Agent[DeepAgentDeps, ResearchReport]:
    """Construct a headless deep agent that researches and returns a report.

    Web search is enabled when ``use_web`` is True (the default) so the agent
    can extend the private RAG findings with public information. ``web_fetch``
    controls Anthropic's server-side page-fetch tool separately — it is
    rejected by most Anthropic-compatible gateways, so it defaults to off when
    a custom ``base_url`` is used.
    Interactive capabilities (filesystem, shell, subagents, planning,
    persistent memory) are disabled — this is a single-shot API task.
    """
    provider = AnthropicProvider(api_key=api_key, base_url=base_url or None)
    anthropic_model = AnthropicModel(model_name=model, provider=provider)

    return create_deep_agent(
        model=anthropic_model,
        instructions=_build_system_prompt(),
        tools=[rag_search, list_collections],
        output_type=ResearchReport,
        # Web tools: search + fetch are independently toggleable. Search is
        # widely supported; the server-side fetch tool is not.
        web_search=use_web,
        web_fetch=web_fetch,
        # Structured synthesis budget.
        model_settings={"max_tokens": max_tokens, "temperature": 0.3},
        # In-memory backend — nothing is written to disk for a single run.
        backend=StateBackend(),
        # Headless API mode: disable interactive capabilities we don't need.
        include_filesystem=False,
        include_subagents=False,
        include_plan=False,
        include_builtin_subagents=False,
        include_skills=False,
        include_memory=False,
        context_manager=False,
        include_history_archive=False,
        cost_tracking=False,
        thinking=False,
    )


async def generate_research_report(
    rag_client: RAGClient,
    query: str,
    *,
    collection_name: str = "documents",
    limit: int = 10,
    api_key: str,
    base_url: str = "",
    model: str = "claude-sonnet-4-20250514",
    max_tokens: int = 32768,
    use_web: bool = True,
    web_fetch: bool = True,
) -> dict[str, Any]:
    """Generate a structured research report using a pydantic-deep agent.

    The agent is given RAG search tools (backed by ``rag_client``) and, when
    ``use_web`` is True, web search capabilities. ``web_fetch`` independently
    controls Anthropic's server-side page-fetch tool. Structured output is
    enforced via ``output_type=ResearchReport``.

    Args:
        rag_client: Connected RAG client.
        query: Research question or topic.
        collection_name: RAG collection to search.
        limit: Number of RAG results to retrieve.
        api_key: Anthropic API key.
        base_url: Optional custom base URL for an Anthropic-compatible gateway.
        model: Claude model name.
        max_tokens: Maximum output tokens.
        use_web: Enable web search to augment RAG findings.
        web_fetch: Enable the server-side web-fetch tool. Most Anthropic-
            compatible gateways reject this tool, so pass False when a custom
            base_url is in use unless the gateway supports it.

    Returns:
        Structured ResearchReport as a dict.
    """
    if not api_key:
        raise ValueError("Anthropic API key is required to run the research agent.")

    agent = _build_research_agent(
        model=model,
        api_key=api_key,
        base_url=base_url,
        max_tokens=max_tokens,
        use_web=use_web,
        web_fetch=web_fetch,
    )
    deps = ResearchDeps(
        backend=StateBackend(),
        rag_client=rag_client,
        collection_name=collection_name,
        rag_limit=limit,
    )

    user_prompt = (
        f"Research the following topic thoroughly:\n\n{query}\n\n"
        "Search the private document store first, then use web sources to fill "
        "gaps where needed. Produce the final structured report."
    )

    # `async with` closes the model's HTTP client after the run so we don't
    # leak connections in the long-running server.
    async with agent:
        result = await agent.run(user_prompt, deps=deps)

    report: ResearchReport = result.output
    report.generated_at = datetime.datetime.now(datetime.UTC).isoformat()
    return report.model_dump()
